#!/bin/sh
set -ex
gcloud run deploy \
	--project=fullstaq-ruby \
	--platform=managed \
	--image=gcr.io/fullstaq-ruby/cloudrun-bug-tcp-cork:latest \
	--cpu=1 \
	--memory=256Mi \
	--max-instances=1 \
	--allow-unauthenticated \
	--region=us-east4 \
	--concurrency=1 \
	--set-env-vars=CORK=true \
	cloudrun-bug-tcp-cork
